### ISSUE TITLE
DateTime not understood as soap primitive

### ISSUE THREAD

**Issue by AdmiralSnyder** [onovotny/SoapFormatter#4]
we're converting a .net framework 4.8 codebase partly to net6, and have to switch to the SoapFormatter package to keep the existing serialized changelogs and external interfaces working and accessable.
while testing for that, the issue with DateTime came up:
Initally, using a simple testcase of a class that merely has a DateTime property, the SoapFormatter stumbled on the missing private Deserialization constructor in System.DateTime in .net6
this was easily solved using a surrogate which merely forwards the GetObjectData call and the actual object in SetObjectData.
this way, the resulting soap xml contained nodes like these:
```xml
<a2:Program_x002B_TestClass id="ref-3" xmlns:a2="http://schemas.microsoft.com/clr/nsassem/ConsoleApp1/ConsoleApp2%2C%20Version%3D1.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3Dnull">
      <Name id="ref-6">Jeff</Name>
      <FirstName id="ref-7">123 Main Street, Redmond, WA 98052</FirstName>
      <DateOfBirth xsi:type="xsd:dateTime">2022-02-08T00:00:00.0000000+01:00</DateOfBirth>
    </a2:Program_x002B_TestClass>
```
where 
```xml
      <DateOfBirth xsi:type="xsd:dateTime">2022-02-08T00:00:00.0000000+01:00</DateOfBirth>
```
Is the crucial part. apparently, the actual date literal string is being serialized without encapsulating it into a property.

This also appears to be the format that the .net framework 4.8 soapformatter serializes `DateTime` properties into.

When now trying to deserialize that, it fails because the `SoapReader.DeserializeComponent method doesn't list `DateTime` as primitive type to use `mapper.ReadInternalSoapValue()` for, and _instead_ tries using `DeserializeISerializableObject()`, which fails because it's expecting a node containing a property name, next (if i undertood the error correctly).

The question now is:
Is adding DateTime to the types at the beginning of the method the __correct__ thing to do?
i.e. instead of 
```cs
                        // in case of String & TimeSpan we should allways use 'ReadInternalSoapValue' method
			// in case of other internal types, we should use ReadInternalSoapValue' only if it is NOT
			// the root object, means it is a data member of another object that is being serialized.
			bool shouldReadInternal = (type == typeof(String) || type == typeof(TimeSpan));
			if(shouldReadInternal || mapper.IsInternalSoapType (type) && (indices != null || parentMemberInfo != null) ) 
			{
				object obj = mapper.ReadInternalSoapValue (this, type);
				
				if(id != 0) 
					RegisterObject(id, obj, info, parentId, parentMemberInfo, indices);

				return obj;
			}
```
do
```cs
                        // in case of String & TimeSpan we should allways use 'ReadInternalSoapValue' method
			// in case of other internal types, we should use ReadInternalSoapValue' only if it is NOT
			// the root object, means it is a data member of another object that is being serialized.
			bool shouldReadInternal = (type == typeof(String) || type == typeof(TimeSpan) || type == typeof(DateTime));
			if(shouldReadInternal || mapper.IsInternalSoapType (type) && (indices != null || parentMemberInfo != null) ) 
			{
				object obj = mapper.ReadInternalSoapValue (this, type);
				
				if(id != 0) 
					RegisterObject(id, obj, info, parentId, parentMemberInfo, indices);

				return obj;
			}
```
thanks for any piece of input.

**Comment by t-johnson** [comment]
Same issue here.  @clairernovotny  would you accept a PR if one of us fix this?  Or was this repo intended to be a direct port of the mono implementation?

I also note that the same issue is logged in the mono repo - see [issue here ](https://github.com/mono/mono/issues/20223)
